namespace Game.Database
{
	public static class NameDB
	{
		public static class Spell
		{
			public const string
				ARCANE_BOLT = "Arcane bolt",
				BASH = "Bash",
				CLEAVE = "Cleave",
				CONCUSSIVE_SHOT = "Concussive shot",
				DEVASTATE = "Devastate",
				DIVINE_HEAL = "Divine heal",
				EXPLOSIVE_ARROW = "Explosive arrow",
				EXPLOSIVE_TRAP = "Explosive trap",
				FIREBALL = "Fireball",
				FORTIFY = "Fortify",
				FRENZY = "Frenzy",
				FROST_BOLT = "Frost bolt",
				HASTE = "Haste",
				HEMORRHAGE = "Hemorrhage",
				INTIMIDATING_SHOUT = "Intimidating Shout",
				METEOR = "Meteor",
				MIND_BLAST = "Mind blast",
				OVERPOWER = "Overpower",
				PIERCING_SHOT = "Piercing shot",
				PRECISE_SHOT = "Precise shot",
				SEARING_ARROW = "Searing arrow",
				SHADOW_BOLT = "Shadow bolt",
				SIPHON_MANA = "Siphon mana",
				SLOW = "Slow",
				SNIPER_SHOT = "Sniper shot",
				STINGING_SHOT = "Stinging shot",
				STOMP = "Stomp",
				VOLLEY = "Volley";
		}
		public static class UI
		{
			public const string ANVIL = "anvil",
				CHEST_COLLECT = "chest_collect",
				CHEST_OPEN = "chest_open",
				CLICK0 = "click0",
				CLICK1 = "click1",
				CLICK2 = "click2",
				CLICK3 = "click3",
				CLICK4 = "click4",
				CLICK5 = "click5",
				CLICK6 = "click6",
				CLOTH_OFF = "cloth_off",
				CLOTH_ON = "cloth_on",
				DRINK = "drink",
				EAT = "eat",
				GLASS_OFF = "glass_off",
				GLASS_ON = "glass_on",
				INVENTORY_CLOSE = "inventory_close",
				INVENTORY_DROP = "inventory_drop",
				INVENTORY_OPEN = "inventory_open",
				INVENTORY_UNEQUIP = "inventory_unequip",
				LEARN_SPELL = "learn_spell",
				LEVEL_UP = "level_up",
				MERCHANT_CLOSE = "merchant_close",
				MERCHANT_OPEN = "merchant_open",
				METAL0_OFF = "metal0_off",
				METAL0_ON = "metal0_on",
				METAL1_OFF = "metal1_off",
				METAL1_ON = "metal1_on",
				MISC_OFF = "misc_off",
				MISC_ON = "misc_on",
				QUEST_ACCEPT = "quest_accept",
				QUEST_FINISH = "quest_finish",
				SELL_BUY = "sell_buy",
				SPELL_BOOK_CLOSE = "spell_book_close",
				SPELL_SELECT = "spell_select",
				TURN_PAGE = "turn_page",
				WOOD_OFF = "wood_off",
				WOOD_ON = "wood_on",
				BLOCK_METAL_METAL = "block_metal_metal",
				BLOCK_WOOD_WOOD = "block_wood_wood",
				BLOCK_METAL_WOOD = "block_metal_wood";
		}
		public static class SaveTag
		{
			public const string
				POSITION = "position",
				ANIM_POSITION = "animPosition",
				INVENTORY = "inventory",
				INVENTORY_SLOTS = "inventorySlots",
				SPELL_BOOK = "spellBook",
				SPELL_BOOK_SLOTS = "spellBookSlots",
				GOLD = "gold",
				WEAPON = "weapon",
				ARMOR = "armor",
				XP = "xp",
				LEVEL = "level",
				HP = "hp",
				MANA = "mana",
				TARGET = "target",
				TALKED_TO = "talkedTo",
				NAME = "name",
				SPAWN_POSITION = "spawnPosition",
				CHARACTER = "character",
				HIT = "hit",
				SPELL = "spell",
				ARMING = "arming",
				TIME_LEFT = "timeLeft",
				TIME = "time",
				COOLDOWNS = "coolDowns",
				IMG_FRAME = "imgFrame",
				MAP = "map",
				DAY_LIGHT = "dayLight",
				STATE = "state",
				STACK = "stack",
				INDEX = "index",
				SLOT = "slot",
				HUD_SLOTS = "hudSlots";
		}
	}
}